"""add language and age_level to books

Revision ID: 22c340f28b59
Revises: 481afe1d1ffc
Create Date: 2026-07-10 09:26:51.289583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22c340f28b59'
down_revision = '481afe1d1ffc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=20), nullable=False, server_default='english'))
        batch_op.add_column(sa.Column('age_level', sa.String(length=20), nullable=False, server_default='5_7'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('age_level')
        batch_op.drop_column('language')

    # ### end Alembic commands ###
