"""add theme_color to books

Revision ID: 3199ed33fb20
Revises: 22c340f28b59
Create Date: 2026-07-12 13:47:19.916704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3199ed33fb20'
down_revision = '22c340f28b59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme_color', sa.String(length=20), nullable=False, server_default='coral'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('theme_color')

    # ### end Alembic commands ###
